### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by mahes-waran** [asapJ/Flutter_Thumbnails#8]
I'm also facing the same issue when I run flutter build apk.
* What went wrong:
Execution failed for task ':thumbnails:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     \.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

      \.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

**Comment by Niko-Kk** [comment]
Had the same issue. Managed to solve it by editing `$FLUTTER_HOME\.pub-cache\hosted\pub.dartlang.org\thumbnails-1.0.1\android\build.gradle` .

Changed the file to look like this

```
group 'com.asapjay.thumbnails'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
```

**Comment by mahes-waran** [comment]
Hi,
  Thank you so much solved this issue.

**Comment by zeeshan-mehdi** [comment]
Love you you saved my day 

thank you very much

**Comment by anilpandey071999** [comment]
thank you brother also worked me

**Comment by hashirawan01** [comment]
where is this file located please help me to find out my app level compilesdk is 33 already@Niko-Kk please help me

**Comment by hashirawan01** [comment]
i stuck here for 2 days and didnt get any solution yet please help me what can i do

**Comment by Niko-Kk** [comment]
@hashirawan01 Quite an old thread, is it the same issue? The versions have changed a lot since then so maybe it's not the same? And if your version is already 33, it might be a different problem...?

**Comment by hashirawan01** [comment]
Yes it's a same issue I just got it change the comile sdk version of whole
app but now I get that how to change the compile sdk version of that plugin

**Comment by Niko-Kk** [comment]
@hashirawan01 Yeah you have to change the plugin min SDK version. You can find the file here `$FLUTTER_HOME\.pub-cache\hosted\pub.dartlang.org\thumbnails-1.0.1\android\build.gradle` after you have ran `pub get` to download the dependency. You should still see it as version 27 as you can see [here](https://github.com/asapJ/Flutter_Thumbnails/blob/9848d149e72b8dee72cd829af67892812b389279/android/build.gradle#L25)

**Comment by hashirawan01** [comment]
Yes thanks a lot man I get it and error was resolved it takes my 2 days
